sudo: required
services: 
  - docker

before_install:
  - docker build -t abhishek1984/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true abhishek1984/react-test npm test 

after_success:
  - docker build -t abhishek1984/multi-nginx ./nginx
  - docker build -t abhishek1984/multi-server ./server
  - docker build -t abhishek1984/multi-worker ./worker
  - docker build -t abhishek1984/multi-client ./client
# Login docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Make images and push to docker hub
  - docker push abhishek1984/multi-nginx 
  - docker push abhishek1984/multi-server
  - docker push abhishek1984/multi-worker
  - docker push abhishek1984/multi-client