sudo: required
services: 
  - docker

before_install:
  - docker build -t abhishek1984/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true abhishek1984/react-test npm test 

after_success:
  - docker build -t abhishek1984/multi-nginx ./nginx
  - docker build -t abhishek1984/multi-server ./server
  - docker build -t abhishek1984/multi-worker ./worker
  - docker build -t abhishek1984/multi-client ./client
# Login docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Make images and push to docker hub
  - docker push abhishek1984/multi-nginx 
  - docker push abhishek1984/multi-server
  - docker push abhishek1984/multi-worker
  - docker push abhishek1984/multi-client

deploy:
  edge: true 
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-759759588288
  bucket_path: docker-multi
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY