version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    depends_on:
      - 'client'
      - 'api'
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api: 
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    expose:
      - '5000'
    environment:
      - REDIS_HOST=redis 
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres       #name of service
      - PGDATABASE=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
  client:
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:  
      - /app/node_modules
      - ./client:/app
    expose:
      - '3000'
  worker:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
